#!/bin/sh
comlist() {
	echo Cписок команд:
	echo [a] - добавить новую запись
	echo [l] - вывести список телефонных номеров
	echo [c] - удалить телефонную книгу
	echo [e] - выйти
	echo [h] - список команд
	echo
}
config_path=~/.config/lr2_z1_chursin
list_path="$config_path/list.txt"
if ! test -d "$config_path"; then
	mkdir "$config_path"
	touch "$list_path"
fi
echo Здравствуйте
echo
comlist
while true; do
	echo "Введите команду:"
	read resp
	echo
	if test "$resp" = e; then
		break;
	elif test "$resp" = h; then
		comlist
	elif test "$resp" = l; then
		echo Список телефонных номеров:
		cat "$list_path"
		echo
	elif test "$resp" = c; then
		rm -R "$config_path"
		break;
	elif test "$resp" = a; then
		echo "Введите имя:"
		read name
		echo "Введите номер телефона:"
		read phone
		echo "$name\t$phone" >> "$list_path"
		echo Запись добавлена
		echo
	else
		echo "Комманда $resp не найдена"
		comlist
	fi
done
echo До свидания
		
	
	
	
	
